version: "3.8"

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - net
  web-server:
    build: ./web-server
    ports:
      - 80:80
    networks:
      - net
  app:
    build: ./app
    volumes:
      - ./app:/app
    networks:
      - net

networks:
  net:
    driver: bridge
