version: "3.8"

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    networks:
      - net
  web-server:
    build: ./web-server
    ports:
      - 80:80
    volumes:
      - ./web-server/default.conf:/etc/nginx/conf.d/default.conf
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
      - ./web-server/content:/usr/share/nginx
    networks:
      - net
  app:
    build: ./app
    networks:
      - net

networks:
  net:
    driver: bridge
